-- ADDITIONAL TOOLKITS
INSERT INTO public.toolkits (name, slug, short_description, description, audience, outcomes, features, icon, access_level, is_featured, display_order, seo_title, seo_description) VALUES
('Small Business AI Toolkit','small-business-ai-toolkit',
 'Prompts for marketing, customer support, operations, and business planning.',
 'A tactical prompt library for founders and small business owners. Generate marketing copy, draft customer support replies, write SOPs, and brainstorm growth strategies without hiring an agency.',
 'Small business owners, solo founders, and freelance entrepreneurs.',
 ARRAY['Write compelling marketing copy','Handle customer support efficiently','Document standard operating procedures','Brainstorm product ideas'],
 ARRAY['Marketing templates','Support scripts','Operations planners','Strategy generators'],
 'store','pro',false,5,
 'Small Business AI Toolkit — Marketing, Support, and Operations Prompts',
 'AI prompts for small businesses to handle marketing, customer support, and operations.'),

('Content Creator AI Toolkit','content-creator-ai-toolkit',
 'Prompts for scripting, content strategy, newsletters, and social media growth.',
 'Beat writer''s block and stay consistent. Prompts to generate video hooks, structure newsletters, plan content calendars, and repurpose long-form content for social media.',
 'YouTubers, newsletter writers, podcasters, and social media managers.',
 ARRAY['Generate engaging video hooks','Structure weekly newsletters','Plan a 30-day content calendar','Repurpose videos into threads'],
 ARRAY['Hook generators','Script templates','Content calendars','Repurposing workflows'],
 'pen-tool','pro',false,6,
 'Content Creator AI Toolkit — Scripting, Strategy, and Social Media Prompts',
 'AI prompts for content creators to plan content, write scripts, and grow their audience.'),

('Researcher AI Toolkit','researcher-ai-toolkit',
 'Prompts for literature reviews, hypothesis generation, and academic writing.',
 'Speed up the tedious parts of academic research. Prompts to summarize papers, format citations, draft literature reviews, and refine research questions.',
 'Academics, PhD candidates, and professional researchers.',
 ARRAY['Summarize dense academic papers','Structure literature reviews','Refine research questions','Draft grant proposals'],
 ARRAY['Paper summarizers','Citation helpers','Literature review structures','Grant writing templates'],
 'microscope','pro',false,7,
 'Researcher AI Toolkit — Literature Reviews and Academic Prompts',
 'AI prompts for academic researchers to summarize papers, draft literature reviews, and write proposals.'),

('Computer Engineering AI Toolkit','computer-engineering-ai-toolkit',
 'Prompts for hardware design, low-level programming, and systems architecture.',
 'Specialized prompts for computer engineering students and professionals. Help with HDL (Verilog/VHDL), C/C++ debugging, embedded systems, and microcontroller programming.',
 'Computer engineering students and embedded systems developers.',
 ARRAY['Debug embedded C code','Write Verilog/VHDL testbenches','Understand microcontroller datasheets','Design system architectures'],
 ARRAY['Hardware debugging workflows','Testbench generators','Datasheet explainers','System design planners'],
 'cpu','pro',false,8,
 'Computer Engineering AI Toolkit — Embedded Systems and Hardware Prompts',
 'AI prompts for computer engineers working with embedded systems, HDL, and low-level programming.'),

('Nigerian Student AI Toolkit','nigerian-student-ai-toolkit',
 'Prompts localized for Nigerian university exams, projects, and NYSC prep.',
 'Navigating the Nigerian university system is unique. Prompts to help with project defense, understanding local grading, writing IT/SIWES reports, and preparing for NYSC.',
 'Students in Nigerian universities (federal, state, and private).',
 ARRAY['Write SIWES/IT reports','Prepare for final year project defense','Plan for NYSC clearance and camp','Understand local academic formatting'],
 ARRAY['Project defense prep','SIWES report generators','NYSC planning guides','Exam revision strategies'],
 'graduation-cap','free',false,9,
 'Nigerian Student AI Toolkit — Project Defense, SIWES, and NYSC Prompts',
 'AI prompts tailored for Nigerian university students focusing on projects, exams, and NYSC.'),

('Interview Prep AI Toolkit','interview-prep-ai-toolkit',
 'Prompts for mock interviews, behavioral questions, and salary negotiation.',
 'Turn anxiety into confidence. Simulate tough interviews, practice the STAR method for behavioral questions, and get scripts for negotiating your salary.',
 'Professionals preparing for job interviews across any industry.',
 ARRAY['Practice behavioral questions (STAR method)','Simulate technical or panel interviews','Prepare smart questions for the interviewer','Script your salary negotiation'],
 ARRAY['Mock interview simulators','STAR method builders','Negotiation scripts','Post-interview follow-ups'],
 'users','pro',false,10,
 'Interview Prep AI Toolkit — Mock Interviews and Negotiation Prompts',
 'AI prompts to help you master job interviews, practice behavioral questions, and negotiate salary.');
